export const TOPICOS_TJCE = [
  // LÍNGUA PORTUGUESA
  { texto: 'Ortografia e acentuação', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Emprego do sinal indicativo de crase', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Compreensão e interpretação de textos', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Denotação e conotação', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Figuras de linguagem', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Morfossintaxe', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Sinonímia e antonímia', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Pontuação', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Concordância nominal e verbal', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Regência nominal e verbal', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },
  { texto: 'Coordenação e subordinação', concurso: 'TJ-CE', materia: 'Língua Portuguesa' },

  // RACIOCÍNIO LÓGICO
  { texto: 'Estrutura lógica de relações', concurso: 'TJ-CE', materia: 'Raciocínio Lógico' },
  { texto: 'Raciocínio verbal e matemático', concurso: 'TJ-CE', materia: 'Raciocínio Lógico' },
  { texto: 'Raciocínio sequencial', concurso: 'TJ-CE', materia: 'Raciocínio Lógico' },
  { texto: 'Proporcionalidade e porcentagem', concurso: 'TJ-CE', materia: 'Raciocínio Lógico' },
  { texto: 'Regra de três simples', concurso: 'TJ-CE', materia: 'Raciocínio Lógico' },
  { texto: 'Medidas de tendência central (moda, mediana, média)', concurso: 'TJ-CE', materia: 'Raciocínio Lógico' },
  { texto: 'Leitura e interpretação de gráficos e tabelas', concurso: 'TJ-CE', materia: 'Raciocínio Lógico' },

  // DIREITOS DAS PESSOAS COM DEFICIÊNCIA
  { texto: 'Lei nº 13.146/2015 — Estatuto da Pessoa com Deficiência', concurso: 'TJ-CE', materia: 'Dir. Pessoas c/ Deficiência' },
  { texto: 'Lei nº 10.098/2000 — Acessibilidade', concurso: 'TJ-CE', materia: 'Dir. Pessoas c/ Deficiência' },
  { texto: 'Lei nº 10.048/2000 — Prioridade de atendimento', concurso: 'TJ-CE', materia: 'Dir. Pessoas c/ Deficiência' },
  { texto: 'Lei nº 8.899/1994 — Transporte coletivo', concurso: 'TJ-CE', materia: 'Dir. Pessoas c/ Deficiência' },
  { texto: 'Decreto 5.296/2004 — Acessibilidade', concurso: 'TJ-CE', materia: 'Dir. Pessoas c/ Deficiência' },

  // LEGISLAÇÃO ESTADUAL
  { texto: 'Lei Estadual nº 9.826/1974 — Estatuto dos Funcionários Públicos do Ceará', concurso: 'TJ-CE', materia: 'Legislação Estadual' },
  { texto: 'Legislação Previdenciária do Ceará', concurso: 'TJ-CE', materia: 'Legislação Estadual' },
  { texto: 'Lei Estadual nº 16.397/2017 — Organização Judiciária do Ceará', concurso: 'TJ-CE', materia: 'Legislação Estadual' },

  // DIR. CONSTITUCIONAL
  { texto: 'Princípios fundamentais da CF/88', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Direitos e garantias fundamentais', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Direitos sociais', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Direitos de nacionalidade e políticos', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Organização do Estado — União, Estados e Municípios', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Administração Pública — disposições gerais', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Poder Executivo', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Poder Legislativo e processo legislativo', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Poder Judiciário — STF, CNJ, STJ', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Ministério Público, Advocacia e Defensoria Pública', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Seguridade Social — Saúde, Previdência e Assistência', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },
  { texto: 'Família, Criança, Adolescente e Idoso', concurso: 'TJ-CE', materia: 'Dir. Constitucional' },

  // DIR. ADMINISTRATIVO
  { texto: 'Princípios da Administração Pública', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Poderes da Administração Pública', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Ato administrativo — conceito e atributos', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Organização administrativa — direta e indireta', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Agentes públicos — Lei nº 8.112/1990', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Processo administrativo — Lei nº 9.784/1999', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Controle da Administração Pública', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Lei de Improbidade — Lei nº 8.429/1992', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Licitações — Lei nº 14.133/2021', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Contratos administrativos', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Serviço público — conceito e princípios', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'Lei de Acesso à Informação — Lei nº 12.527/2011', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },
  { texto: 'LGPD — Lei nº 13.709/2018', concurso: 'TJ-CE', materia: 'Dir. Administrativo' },

  // DIR. CIVIL
  { texto: 'Lei de Introdução às Normas do Direito Brasileiro', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Pessoas naturais — personalidade e capacidade', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Pessoas jurídicas', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Negócio jurídico — conceito e defeitos', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Prescrição e decadência', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Obrigações — modalidades e extinção', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Contratos em geral', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Responsabilidade civil', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Direito das coisas — posse e propriedade', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Direito de família', concurso: 'TJ-CE', materia: 'Dir. Civil' },
  { texto: 'Direito das sucessões', concurso: 'TJ-CE', materia: 'Dir. Civil' },

  // PROC. CIVIL
  { texto: 'Princípios gerais do processo civil', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Jurisdição, ação e processo', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Competência — absoluta e relativa', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Partes e procuradores', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Atos processuais — prazos e citação', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Tutela provisória', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Procedimento comum — petição inicial', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Provas — modalidades e ônus', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Sentença e coisa julgada', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Recursos — apelação, agravo e embargos', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Processo de execução', concurso: 'TJ-CE', materia: 'Proc. Civil' },
  { texto: 'Lei nº 9.099/1995 — Juizados Especiais', concurso: 'TJ-CE', materia: 'Proc. Civil' },

  // DIR. PENAL
  { texto: 'Princípios do Direito Penal', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Aplicação da lei penal no tempo e no espaço', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Ilicitude e culpabilidade', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Concurso de pessoas e penas', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Prescrição e extinção da punibilidade', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Crimes contra a pessoa', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Crimes contra o patrimônio', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Crimes contra a fé pública', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Crimes contra a Administração Pública', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Lei de Abuso de Autoridade — Lei nº 13.869/2019', concurso: 'TJ-CE', materia: 'Dir. Penal' },
  { texto: 'Lei de Lavagem de Dinheiro — Lei nº 9.613/1998', concurso: 'TJ-CE', materia: 'Dir. Penal' },

  // PROC. PENAL
  { texto: 'Princípios do processo penal', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Inquérito policial', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Ação penal', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Jurisdição e competência', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Provas no processo penal', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Prisão, medidas cautelares e liberdade provisória', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Procedimento comum e tribunal do júri', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Nulidades e recursos', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Juizados Especiais Criminais — Lei nº 9.099/1995', concurso: 'TJ-CE', materia: 'Proc. Penal' },
  { texto: 'Lei de Execução Penal — Lei nº 7.210/1984', concurso: 'TJ-CE', materia: 'Proc. Penal' },
];